version: '3.9'

services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: react_with_spring_boot_and_kotlin
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - erudio-network

  rest-react-kotlin-server:
    image: rest-react-kotlin-server
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/react_with_spring_boot_and_kotlin?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: docker
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge
